### ISSUE TITLE
1.0.0 Release

### ISSUE THREAD

**Issue by darkfrog26** [typelevel/squants#151]
We should figure out if any of the remaining tickets need to be addressed before an official 1.0.0 release is made. I'd prefer to get this done ASAP to avoid depending on a SNAPSHOT.

Are there any tickets that specifically need to be addressed before the current status is considered "stable"?

**Comment by cquiroz** [comment]
👍  for a quick 1.0.0 release

**Comment by derekmorr** [comment]
Question for @garyKeorkunian : was there anything holding you back from a 1.0? Was there a vision for the project that hasn't yet been met? Are there APIs that are still in flux? I'd think users would expect the API to stay fairly stable once it hits 1.x.

**Comment by garyKeorkunian** [comment]
One of the items that I've worked on sporadically over the past year or so, is to replace the Double used for the underlying value with a generic.  This would allow users to specify a more precise type, such as those available from Spire.

A sandbox for that work can be found in the /test/experimental folder.  A description can be found in the Wiki [SQUIP-1](https://github.com/typelevel/squants/wiki/SQUIP-1:-Generic-Type-for-Underlying-Quantity-Value).  It's slow going as I've played a lot of type system wack-a-mole and haven't been able to get it all working.  Most difficulty at this point is around the QuantityRange.

I was hoping to get that in before a 1.0 release because it would result in an API change.  Although, there may be a way to get that generic to default to a Double so that the impact on existing code is minimized.

That said, there is no reason to stop a 1.0 release from happening.  If the improvement noted above is something we want to move forward with, however, it may warrant a major release version increment when ready.

**Comment by derekmorr** [comment]
Agreed. I think we're good for a 1.0 release. That sort of change would be nice to see, but probably in a 2.x.

**Comment by golem131** [comment]
👍 for a quick 1.0.0 release

**Comment by cquiroz** [comment]
The release is on sonatype though it seems to take a while to sync to maven central

**Comment by cquiroz** [comment]
Release in complete with the artifacts available in maven central

**Comment by darkfrog26** [comment]
I believe you forgot to `+publishSigned` and only 2.12 got released.

**Comment by cquiroz** [comment]
I see all of them on maven (Look for the squants dirs)

https://repo1.maven.org/maven2/org/typelevel/

**Comment by darkfrog26** [comment]
Yeah, I see them, but for some reason it wasn't resolving.  I may have something screwed up in my ivy cache.  Sorry about that.
