### ISSUE TITLE
Loss of precision in Money when using Multiplication

### ISSUE THREAD

**Issue by alexkok8** [typelevel/squants#265]
While using the Squants library to work with the Money type, I encountered a loss of precision when doing certain calculations. I instantiate the money object by using the Currency object and multiply it with an Integer. In this example: `EUR(9709.06)` as Money and `4992` as Integer.

I tried to instantiate it by using the BigDecimal, as it might be related to the double that we pass to the currency object. (By using `EUR(BigDecimal(9709.06))` or `EUR(BigDecimal("9709.06"))`)
However, this didn't solve the problem, actually I received the same results.

An example to reproduce this:
```
scala> val x: Int = 4992; val y: Money = EUR(9709.06)
x: Int = 4992
y: squants.market.Money = 9709.06 EUR

scala> x * y == y * x
res29: Boolean = true

scala> x * y compareTo y * x
res30: Int = 0

scala> x * y + x * y == (y * x) * 2
res31: Boolean = false
// expected true

scala> x * y + x * y compareTo (y * x) * 2
res32: Int = 1
// expected 0

scala> x * y + x * y amount
warning: there was one feature warning; re-run with -feature for details
res33: BigDecimal = 96935255.039999992

scala> (y * x) * 2 amount
warning: there was one feature warning; re-run with -feature for details
res34: BigDecimal = 96935255.03999999
```

**Comment by garyKeorkunian** [comment]
This was mentioned in #233 but was a bit out of scope for that issue.
 
Here's the background:

Money stores the underlying `amount` as BigDecimal.  However, because it's a Quantity, the `value` field is still a Double, that is a Double representation of the `amount`.

`Money * Int|Double` will call  the `Quantity.*` method which acts on the `value` field, thus the loss of precision.  We can be fixed by creating an overridden methods for `Money.*`

The other issue is when leading the operation with the Int|Double.  This uses SquantifiedLong which also uses the `value` field.  We should be able to fix this by adding a `*(Money)` method to SquantifiedLong/Double or something similar.

In the meantime, one way to fix the example above is to ensure that the operand is also a BigDecimal and that the Money operand leads the operation.  This ensures that the operation is carried out by the `Money.*(BigDecimal)` method, which will do BD math.

```scala
val x= BigDecimal(4992)
val y = EUR(9709.06)

y * x + y * x == (y * x) * 2 // returns true
```

I will take on these changes.
