### ISSUE TITLE
Add support for ZAR and NAD currencies

### ISSUE THREAD

**Issue by ecamellini** [typelevel/squants#291]
We use `squants` in our project to handle money and currencies, and we need to handle some values in `ZAR` (South Australian Rand) and `NAD` (Namibian Dollar). 

We added the two currencies to our model as follows:

```scala
object ZAR extends Currency("ZAR", "South African Rand", "R", 2)
object NAD extends Currency("NAD", "Namibian Dollar", "N$", 2)
```

We would need to add them also to the `defaultCurrencySet`:
https://github.com/typelevel/squants/blob/81cfd3d5271bafc3ccf57c9437c4c0ca4cedb206/shared/src/main/scala/squants/market/package.scala#L58
so that the following constructor works:
https://github.com/typelevel/squants/blob/720a6ba692f09b026a93bd42ad7a0557b06e23fe/shared/src/main/scala/squants/market/Money.scala#L390

Otherwise, when instantiating `Money` with the string `"ZAR"` as second argument we get an exception:

![image](https://user-images.githubusercontent.com/6418684/34716359-e77ee924-f52f-11e7-980c-0f92c3b0ac6a.png)
(we receive string values from an external API, so we need to use such constructor)

It would be nice to have all this directly integrated in squants by adding support for the two currencies.

**Comment by ecamellini** [comment]
I can also work on this unless someone else wants to work on it

**Comment by ecamellini** [comment]
It would also be good to make the `defaultCurrencySet` overridable/extensible in some way (with an `implicit`, for example).  This would allow to add new currencies locally and still be able to use the constructor with `String` currency without the need to modify `squants` itself.

**Comment by bytecodeguru** [comment]
Thank you @garyKeorkunian for your support.

This still does not fix the original issue: creating values using factories that take Currency Code (String) for new currencies.

For example in this existing test: https://github.com/typelevel/squants/blob/569e0608716580b568147e14860349b207c0a0f1/shared/src/test/scala/squants/market/MoneySpec.scala#L33

adding the following line compiles but the test fails:
```
Money(10, "ZAR") should be(Money(10, ZAR))
```

It seems to me that the root cause is that

https://github.com/typelevel/squants/blob/569e0608716580b568147e14860349b207c0a0f1/shared/src/main/scala/squants/market/package.scala#L58

should include all supported currencies and/or possibly be modified by squants users. Otherwise this Money constructor can't work for new currencies:

https://github.com/typelevel/squants/blob/569e0608716580b568147e14860349b207c0a0f1/shared/src/main/scala/squants/market/Money.scala#L390

**Comment by garyKeorkunian** [comment]
@bytecodeguru Yes, you are correct.  I added the feature to MoneyContext as it is a class and was easy to do.  But as you said that doesn't help with Money factory.  The val defaultCurrencySet is immutable, which prevents it from being updated from outside the library, and so will need another approach.  This is true of all Dimensions, and the changes necessary will likely break backward compatibility.

**Comment by bytecodeguru** [comment]
Should we reopen this issue to at least include `ZAR` and `NAD` into `defaultCurrencySet` instead of a brand new issue?

**Comment by garyKeorkunian** [comment]
No, I'll just make that fix and submit PR.
