### ISSUE TITLE
no automatic conversion for java.math.BigInteger?

### ISSUE THREAD

**Issue by dportabella** [typelevel/squants#308]
```
val v = java.math.BigInteger.valueOf(12345)
def f(v: BigInt) { println(s"Ok $v") }
f(v)  // the automatic conversion works.

import $ivy.`org.typelevel::squants:1.3.0`, squants.information._
Bytes(v)          // cmd4.sc:1: could not find implicit value for parameter num: Numeric[java.math.BigInteger]

Bytes(BigInt(v))  // res2: Information = 12345.0 B
```

**Comment by hunterpayne** [comment]
This is happening because you are requiring chaining two implicit conversions in a row (BigInteger -> BigInt -> Double).  What's even weirder is that Bytes should probably be a Long (there is another issue open about that).  Just make an implicit conversion between BigInteger and Double and this should work for you (until Bytes switches to use Long that is :) )

**Comment by dportabella** [comment]
thx!
