### ISSUE TITLE
Can't reliably mix Money and Time

### ISSUE THREAD

**Issue by acarrasco** [typelevel/squants#311]
Time does an internal conversion of the magnitude to Double no matter what type of number is used when constructing the objects, so that causes problems when working with Money (which shouldn't lose precision).

This simple worksheet shows the error:
```
import squants.market._
import squants.time._
val price = Price(GBP(BigDecimal("0.3")), Seconds(1)) //price: squants.market.Price[squants.time.Time] = 0.3 GBP/1.0 s this is OK, the price is stored internally as a BigNum
price * Seconds(3)  // res0: squants.market.Money = 0.8999999999999999 GBP this is wrong, it should be 0.9 GBP
```

**Comment by acarrasco** [comment]
Here is the culprit:
https://github.com/typelevel/squants/blob/master/shared/src/main/scala/squants/time/Time.scala#L60

**Comment by derekmorr** [comment]
With the exception of Money, all quantities in squants use Double internally. These sort of floating point errors are a known side effect of that.

There have been some discussions around overhauling the library to use a generic numeric type, which would let users use arbitrary numeric types, but this isn't minor change, and isn't being actively worked on.

For now, the rounding error you've reported is expected behavior.

**Comment by acarrasco** [comment]
Thanks! Good to know that it's a known limitation :)
I'm going to take a deeper look myself, maybe I can find an acceptable workaround.

**Comment by acarrasco** [comment]
@derekmorr the workaround I was thinking of is already implemented in the current master! :D
I'm adding a test for it and sending a PR
