### ISSUE TITLE
Ser/des of units for runtime comparisons

### ISSUE THREAD

**Issue by acruise** [typelevel/squants#331]
I'd like to be able to offer units metadata in my system, so that when someone takes a metric defined as RPM and tries to add it to a US Dollars quantity, the system can warn them that it's a nonsensical operation.  

The compile-time functionality provided by this library is good, but AFAICT irrelevant to my use case. I'm open to suggestions about alternative ways to achieve this goal outside this library, but this seemed like a good place to ask for it. :)

**Comment by hunterpayne** [comment]
I'm not quite sure what you are asking here.  I'm guessing RPM is a currency (although to me its a rate of either requests or revolutions).  I'm going to try to answer you question but if I answer the wrong question, this is why.

The fit of currencies into the scientific mindset of squants is a bit weird for someone who works in fx.  Most of the dimensions in Squants comes from physics or other scientific fields.  So the idea of changing conversions rates seems a bit weird in this project.  If you think of an e-commerce system where maybe an exchange rate table is provided at some period (e.g. daily), then how a fx system might work you can see there isn't one desired solution here.  That's why the Money code is a bit different from the rest of the source base.  

If you don't want a currency type to be convertible to another currency, you probably just want to roll your own type.  
If you want to be able to control the conversion rate between currencies, then you probably want to implement your own custom MoneyContext.

**Comment by acruise** [comment]
By "RPM" I meant revolutions per minute... I'm not as interested in currency conversions right now, but different physical units of measure would be valuable metadata for me. :)

**Comment by hunterpayne** [comment]
Well turbineRotSpd would be a Frequency and timeSinceLastMaint would be a Time and a Frequency * Time is a Dimensionless (number of rotations in your case).  Squants prevents you from adding Frequency to Money as you mentioned in your first post.  And a rotation is just an event which is why you end up with a Dimensionless at the end.  If you want something more mathematically based, there is [Spire](https://github.com/non/spire).

As I'm still not quite sure what you are doing, I'm going to make a suggestion.  When you pull from config, pull a string that squants can read into an Squants object.  Then when a user tries to do something, compile a bit of scala that tried to do the thing the user is requesting, converting to Dollars from RPMs or something.  If it compiles, great, run the code and it can give you an answer.  If it doesn't, then return the error to the user.  I have no idea if this is sane or not as I still have no idea what you are doing.  Maybe if you explain your use case more fully, I could give you a better answer.

**Comment by acruise** [comment]
hmm, not a bad idea, thanks!
