### ISSUE TITLE
Handling of PRs

### ISSUE THREAD

**Issue by cquiroz** [typelevel/squants#338]
Hi

We have a collection of PRs awaiting approval and merging. I've been reviewing and approving some but I've refrained from merging awaiting for a second opinion.

This has stalled the process as it seems I'm the only one doing it. If you guys are ok I can take care of merging changes and making releases by myself but I don't want to step on other's toes

Please let me know if that's ok or suggest any alternatives

/cc @garyKeorkunian @derekmorr @darkfrog26 @golem131 @sarahgerweck @vitorsvieira

**Comment by darkfrog26** [comment]
Sorry, @cquiroz, I'd love to help, but I'm a bit overwhelmed and behind with my own projects at the moment and don't have the time to contribute to this one. Hopefully, when my time frees up a bit I'll be able to contribute more time to this project.

**Comment by hunterpayne** [comment]
So I guess we should think of this project as dead?  Maybe you should tell users to go somewhere else if nobody can be bothered to admin it?

**Comment by cquiroz** [comment]
I don't mind doing the admin chores but I don't want to step on anybody's toes. it would be good to get more support from other commiters

**Comment by hunterpayne** [comment]
There are few things in life more frustrating than being able to do something you need to do but not being given the permission to do it.  The users bothered to take their own time and make the PRs for you.  You can't be bothered to put even 30 minutes of time into maintaining this project to approve these PRs.  But also, you can't be bothered to let others do it.  

That really doesn't make you or your company look good.  If you can't do it, don't bother apologizing again.  That's just dishonest.  Be honest and tell this project's users that you just don't care about them at all and that this project is well and truly dead.  Then maybe someone will fork it and maintain it.  Otherwise, you are doing more harm than good.  Getting stranded using an unmaintained project is no fun and by saying you will maintain it but not doing it, you are inviting more coders to get stranded.

**Comment by garyKeorkunian** [comment]
Hello, all.  I have gone through the outstanding PR's and approved a few.  Some need to update before they can be merged.

@hunterpayne Your PR has been merged.  Sorry for the delay, but participation is light.

As far as this not making  "our" company look good, there is no company, no SLA, no support contracts.  Just a small group of volunteers doing what they can to mature the library.  That said, it is very far from a dead project.  It is stable and used in many projects.  I started the project at my last company, Viridity Energy, where they sponsored all of my time on the project (they still use the library, but have no active contributors now, as it works for them as is).  I've since moved on to a company that has no use-case for Squants, so my time on this project has been quite limited.  Due to the lack of attention it was getting, Typelevel agreed to bring it under their umbrella for hosting primarily, but they do not sponsor contributions to the project.  I understand your frustration, but @derekmorr, @cquiroz, @darkfrog26  (and others) have done quite a bit nurture this project, but without the commitment from an employer or other sponsors, the time we have to put into this is limited.

We do appreciate your PR, but reviews are important and our time constrained.  We don't want to merge things without close review and discussion, lest we risk breaking the library for others.

All that said, if you and your employer find this library valuable, perhaps they would be willing to allocate some of your time towards being a maintainer so that you can help review and approve PR's.  If that's something you can do, let us know.

**Comment by hunterpayne** [comment]
@garyKeorkunian everyone appreciates you merging PRs yesterday.  I'm sorry I had to post that to get you to act.  But in my defense, I (and the other users) had tried other tactics.  We made PRs, we posted issues, we said nice things in an effort to get you to pay attention.  When all those things were exhausted, there was only one tactic left.  If you ignore your user base, you are essentially training your users to do what I did to get your attention.  If being nice and waiting patiently had worked, we wouldn't be having this conversion.  If you respond to users in a shorter time frame, they won't have to resort to such tactics.

If you go back and reread what I wrote yesterday, what I was really asking for was a decision: either yes we will maintain this project or no we can't continue to maintain this project.  After 15 months of silence, its a reasonable question to ask.  You have answered that question nicely.  Thank you.  I will delete all my posts on this issue tomorrow.  I just wanted to give you an explanation for my post.  It wasn't out of malice; it was a calculated move because it was clear that nothing else was working.

**Comment by derekmorr** [comment]
@hunterpayne You could always volunteer to be a maintainer if you use this project and are concerned about its future. That's how I became a maintainer. However, I now don't use squants much (or even Scala). But please keep in mind that no one on this project owes you anything. Like @garyKeorkunian said, we're all unpaid volunteers.

**Comment by hunterpayne** [comment]
Which is perhaps why I waited quite some time before posting.  I just wanted a decision about the future of the project, not necessarily action although the action was appreciated.  I don't want to make you feel unappreciated, but please consider if you really want to make someone feel unappreciated ignore their PR for a few months.  If you do that to people enough, my rather tame response on this thread is about the best you can expect in the long run.  This works in all walks of life, not just opensource projects.  The golden rule is a real thing...

PS We really do appreciate all your hard work on this project...all of you.
