### ISSUE TITLE
Temperature differences are not in °C

### ISSUE THREAD

**Issue by nornagon** [typelevel/squants#42]
I feel like `12.C - 3.C < 20.K` should work.

**Comment by kyzn** [comment]
I think this is also related:

```
scala> Fahrenheit(59).in(Celsius)
res74: squants.thermal.Temperature = 15.0°C

scala> Celsius(10)+Fahrenheit(59).in(Celsius)
res75: squants.thermal.Temperature = 25.0°C

scala> Celsius(10)+Fahrenheit(59)
res76: squants.thermal.Temperature = 42.77777777777778°C
```

**Comment by darkfrog26** [comment]
If you want to compare numbers then you can already do so by just getting the numeric value from the type and comparing.  The purpose of this library, as I see it is a representation of comparison relating to the specific types so the way it works, in my opinion, is the only way it should work.  I'd vote to close this ticket.

**Comment by darkfrog26** [comment]
Closing this issue since no one seems to be defending the position. Please re-open if there is still something to be settled here.

**Comment by psung** [comment]
I realize that this is the way it is for now, but it would be nice to implement something like the separation of Celsius and CelsiusScale (akin to Time vs. Duration) when there is an opportunity for an API-breaking change. Some examples:

```
Celsius(37) + Celsius(45) // should not compile
Celsius(37) + CelsiusScale(5) // ==> Celsius(42)
Celsius(45) - Celsius(37) // ==> CelsiusScale(8)
Celsius(40) - Celsius(30) < Celsius(15) // should not compile
Celsius(40) - Celsius(30) < CelsiusScale(15) // true
```

And in particular one motivating use case is a TemperatureRamp dimension (or similarly, code to work with specific heat or heat capacity), where without a distinction between Foo and FooScale it is quite easy to write nonsensical things:

```
Celsius(45) / Seconds(5) // should not compile
CelsiusScale(45) / Seconds(5) // ==> CelsiusDegreesPerSecond(9)
CelsiusDegreesPerSecond(1) * Seconds(5) // ==> CelsiusScale(5)
CelsiusDegreesPerSecond(1) * Seconds(5) < Celsius(35) // should not compile
Celsius(30) + CelsiusDegreesPerSecond(0.2) * Seconds(10) // ==> Celsius(32)
```

(Alternatively, instead of having this land in an API-breaking 2.0 release, classes with the new behavior could be introduced in a separate package; is there any precedent for how you'd like such things to be done in squants?)
